<a href="https://colab.research.google.com/github/why-does-ie-still-exist/Lin-Alg-for-Robotics-71R/blob/main/Lin_Alg_for_Forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from math import *

upperlen = .11
lowerlen = .11
plateoffset = .05
upperrot = pi/2
lowerrot = 0
baserot = pi/2

In [ ]:
A0toE = np.array([0,0,upperlen])
A0toE

array([0.  , 0.  , 0.11])

In [ ]:
#we're rotating in the z-axis, assuming B is aligned with the normal coordinate system
matrixFromAtoB = np.array([
                           [cos(upperrot), 0, -sin(upperrot)],
                           [0, 1, 0,],
                           [sin(upperrot), 0, cos(upperrot)],
])
matrixFromAtoB

array([[ 6.123234e-17,  0.000000e+00, -1.000000e+00],
       [ 0.000000e+00,  1.000000e+00,  0.000000e+00],
       [ 1.000000e+00,  0.000000e+00,  6.123234e-17]])

In [ ]:
B0toA0 = np.array([0,0,lowerlen])

B0toE = B0toA0 + np.matmul(matrixFromAtoB, A0toE)
B0toE

array([-0.11,  0.  ,  0.11])

In [ ]:
matrixfromBtoC = np.array([
                           [cos(baserot), -sin(baserot),0],
                           [sin(baserot), cos(baserot), 0],
                           [0,0,1],
])

C0toE = np.matmul(matrixfromBtoC, B0toE)
C0toE

array([-6.7355574e-18, -1.1000000e-01,  1.1000000e-01])

In [ ]:
D0toC0 = [0,0,plateoffset],

D0toE = D0toC0 + C0toE
D0toE

array([[-6.7355574e-18, -1.1000000e-01,  1.6000000e-01]])