<a href="https://colab.research.google.com/github/why-does-ie-still-exist/Lin-Alg-for-Robotics-71R/blob/main/Lin_Alg_for_Forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from math import *

upperlen = .11
lowerlen = .11
plateoffset = .05
upperrot = pi/2
lowerrot = pi/2
baserot = pi/2

In [2]:
A0toEinA = np.array([0,0,upperlen])
A0toEinA

array([0.  , 0.  , 0.11])

In [3]:
#we're rotating in the z-axis, assuming B is aligned with the normal coordinate system
matrixFromAtoB = np.array([
                           [cos(upperrot), 0, -sin(upperrot)],
                           [0, 1, 0,],
                           [sin(upperrot), 0, cos(upperrot)],
])
matrixFromAtoB

array([[ 6.123234e-17,  0.000000e+00, -1.000000e+00],
       [ 0.000000e+00,  1.000000e+00,  0.000000e+00],
       [ 1.000000e+00,  0.000000e+00,  6.123234e-17]])

In [4]:
B0toA0inB = np.array([0,0,lowerlen])

B0toEinB = B0toA0inB + np.matmul(matrixFromAtoB, A0toEinA)
B0toEinB

array([-0.11,  0.  ,  0.11])

In [5]:
matrixfromBtoC = np.array([
                           [cos(lowerrot), 0, -sin(lowerrot)],
                           [0, 1, 0,],
                           [sin(lowerrot), 0, cos(lowerrot)],
])

C0toE = np.matmul(matrixfromBtoC, B0toEinB)
C0toE

array([-0.11,  0.  , -0.11])

In [6]:
matrixfromCtoD = np.array([
                           [cos(baserot), -sin(baserot),0],
                           [sin(baserot), cos(baserot), 0],
                           [0,0,1],
])
C0toEinD = np.matmul(matrixfromCtoD, C0toE)
D0toC0inD = [0,0,plateoffset],

D0toEinD = D0toC0inD + C0toEinD
D0toEinD

array([[-6.7355574e-18, -1.1000000e-01, -6.0000000e-02]])